#!/usr/bin/env bash
# Port of dummy-certs-linux in the original DQ9 server's windows-msbuild.yml.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output="${1:-$root/certs}"
mkdir -p "$output"
temporary="$(mktemp -d)"
trap 'rm -rf "$temporary"' EXIT

curl --fail --location --silent --show-error \
  'https://larsenv.github.io/NintendoCerts/WII_NWC_1_CERT.p12' \
  --output "$temporary/WII_NWC_1_CERT.p12"

# Original workflow extracts the certificate and private key from keys.txt
# using fixed line ranges. The format-independent openssl selectors avoid
# depending on the line numbers generated by the installed OpenSSL version.
openssl pkcs12 -legacy -in "$temporary/WII_NWC_1_CERT.p12" \
  -passin pass:alpine -clcerts -nokeys -out "$output/nwc.crt"
openssl pkcs12 -legacy -in "$temporary/WII_NWC_1_CERT.p12" \
  -passin pass:alpine -nocerts -nodes -out "$temporary/nwc.key"
openssl genrsa -out "$output/server.key" 1024
openssl req -new -key "$output/server.key" -out "$temporary/server.csr" \
  -subj '/C=US/ST=Washington/L=Redmond/O=Nintendo of America Inc./OU=Nintendo Wifi Network/CN=*.*.*/emailAddress=ca@noa.nintendo.com'
openssl x509 -req -in "$temporary/server.csr" -CA "$output/nwc.crt" \
  -CAkey "$temporary/nwc.key" -CAcreateserial -CAserial "$temporary/nwc.srl" \
  -out "$output/server.crt" -days 3650 -sha1 \
  -extfile "$root/openssl-nitro.cnf" -extensions nitro_leaf
cat "$output/server.crt" "$output/nwc.crt" > "$output/server_with_chain.crt"
