import { createScriptCommands } from "./script-commands.js";
import { createInputCommands } from "./input-commands.js";
import { createRuntimeCommands } from "./runtime-commands.js";
import { createRomCommands } from "./rom-commands.js";
import { createSaveCommands } from "./save-commands.js";
import { createStateCommands } from "./state-commands.js";
import { createRecentFileCommands } from "./recent-file-commands.js";
import { createScreenshotCommands } from "./screenshot-commands.js";
import { createMemoryCommands } from "./memory-commands.js";
import { createDisassemblyCommands } from "./disassembly-commands.js";
import { createDebuggerControlCommands } from "./debugger-control-commands.js";
import { createContextCommands } from "./context-commands.js";
import { createUtilityCommands } from "./utility-commands.js";
import { createFeatureCommands } from "./feature-commands.js";

export function createCommands(context) {
    const {
        ANALYSIS_BASELINE_SLOT_PREFIX,
        ANALYSIS_BASELINE_STATE_FORMAT_VERSION,
        analysisBaselineSlotToken,
        applyFreezes,
        applyScaleRotation,
        applySaveAndReloadRom,
        bigEndianValue,
        blockSaveFlush,
        bootWaitMs,
        breakpointOwners,
        bytesFromFlexibleParams,
        bytesFromParams,
        cancelAndWait,
        cancelOperation,
        copyText,
        currentRomIdentity,
        dispatchScriptEvent,
        dispatchScriptEventAndWait,
        download,
        drawFrame,
        drawLoadedStateFrame,
        emulatorActivity,
        ensureReady,
        ensureRomLoaded,
        ensureWasmReady,
        frameService,
        fileTransactionService,
        formatDisassemblyText,
        getPc,
        getRegisters,
        hasLoadedRom,
        hex,
        idbGet,
        idbKeys,
        idbDelete,
        idbPut,
        instructionWidthForMode,
        isAnalysisBaselineSlot,
        loadStateBytesFromMemory,
        log,
        matchSearchCondition,
        memorySearchRangeKey,
        memorySearchRanges,
        modeNumber,
        native,
        onScreenValid,
        operationManager,
        inputTaskManager,
        getInputParentSignal,
        opcodeWordsFromInput,
        openPicker,
        parseAddress,
        parseNumber,
        pauseForFileLoad,
        publicCallStackData,
        publicOtherCoroutines,
        pumpAudio,
        queueAutoUpdateLoop,
        readAnalysisBaseline,
        readCallStackData,
        readFileFromInput,
        readSized,
        requireValidScreen,
        recordRecentFile,
        refreshDebuggerViews,
        reloadCurrentRom,
        rememberSlot,
        renderBreakpoints,
        renderCallStack,
        renderFreezes,
        renderHotkey,
        renderMemoryDump,
        renderRecentFiles,
        renderRegisters,
        renderScriptConsole,
        restoreAfterFileLoad,
        runCommand,
        runDebuggerInstruction,
        runIsolatedScript,
        runSandboxBoundarySelfTest,
        runTraceStepper,
        runUntilNextBranchOrReturn,
        runUntilTrueNextBranch,
        saveKeymap,
        scriptSummary,
        listPScriptMcps,
        callPScriptMcp,
        setKey,
        setTouchState,
        sha256Hex,
        shouldIncludeDisassemblyBytes,
        snapshotContext,
        splitBinaryBits,
        startPersistentScript,
        state,
        stopAfterFailedStateLoad,
        stopAutoUpdateLoop,
        stopPersistentScript,
        swap16,
        swap32,
        syncNativeBreakStatus,
        tick,
        toButtonList,
        u16FromBytes,
        u32FromBytes,
        ui,
        uiInteractionLock,
        updateStatus,
        wakeEmulationLoop,
        waitChecked,
        waitForInputWindow,
        writeAnalysisBaseline,
        writeRomFile
    } = context;

    const commands = {
        ...createContextCommands({
            ANALYSIS_BASELINE_SLOT_PREFIX,
            analysisBaselineSlotToken,
            call: (name, params) => commands[name](params),
            currentRomIdentity,
            emulatorActivity,
            ensureRomLoaded,
            fileTransactionService,
            getRegisters,
            hasLoadedRom,
            idbGet,
            idbKeys,
            idbDelete,
            idbPut,
            native,
            operationManager,
            readAnalysisBaseline,
            sha256Hex,
            snapshotContext,
            state,
            syncNativeBreakStatus,
            ui,
            writeAnalysisBaseline
        }),
        ...createRomCommands({
            state,
            ui,
            native,
            cancelAndWait,
            dispatchScriptEventAndWait,
            fileTransactionService,
            ensureReady,
            ensureWasmReady,
            bytesFromParams,
            readFileFromInput,
            openPicker,
            pauseForFileLoad,
            restoreAfterFileLoad,
            stopAfterFailedLoad: stopAfterFailedStateLoad,
            writeRomFile,
            reloadCurrentRom,
            bootWaitMs,
            log
        }),
        ...createSaveCommands({
            state,
            ui,
            native,
            cancelAndWait,
            dispatchScriptEventAndWait,
            fileTransactionService,
            ensureReady,
            ensureRomLoaded,
            readFileFromInput,
            openPicker,
            pauseForFileLoad,
            restoreAfterFileLoad,
            stopAfterFailedLoad: stopAfterFailedStateLoad,
            applySaveAndReloadRom,
            bootWaitMs,
            rememberSlot,
            idbGet,
            idbPut,
            recordRecentFile,
            download,
            log
        }),
        ...createStateCommands({
            analysisBaselineSlotToken,
            blockSaveFlush,
            bytesFromParams,
            cancelAndWait,
            dispatchScriptEvent,
            dispatchScriptEventAndWait,
            download,
            drawLoadedStateFrame,
            ensureReady,
            ensureRomLoaded,
            idbGet,
            idbPut,
            isAnalysisBaselineSlot,
            loadStateBytesFromMemory,
            log,
            native,
            fileTransactionService,
            openPicker,
            pauseForFileLoad,
            readFileFromInput,
            recordRecentFile,
            rememberSlot,
            restoreAfterFileLoad,
            state,
            stopAfterFailedStateLoad,
            ui
        }),
        ...createRecentFileCommands({
            applySaveAndReloadRom,
            blockSaveFlush,
            bootWaitMs,
            cancelAndWait,
            dispatchScriptEventAndWait,
            fileTransactionService,
            drawLoadedStateFrame,
            ensureReady,
            ensureRomLoaded,
            idbGet,
            loadStateBytesFromMemory,
            native,
            pauseForFileLoad,
            rememberSlot,
            renderRecentFiles,
            restoreAfterFileLoad,
            state,
            stopAfterFailedStateLoad,
            ui
        }),
        ...createScreenshotCommands({
            requireValidScreen,
            state,
            ui
        }),
        ...createRuntimeCommands({
            applyFreezes,
            applyScaleRotation,
            bootWaitMs,
            cancelAndWait,
            cancelOperation,
            fileTransactionService,
            dispatchScriptEvent,
            dispatchScriptEventAndWait,
            drawFrame,
            ensureReady,
            ensureRomLoaded,
            frameService,
            hasLoadedRom,
            native,
            onScreenValid,
            pauseEventService: context.pauseEventService,
            pauseForFileLoad,
            pumpAudio,
            queueAutoUpdateLoop,
            reloadCurrentRom,
            restoreAfterFileLoad,
            state,
            stopAfterFailedLoad: stopAfterFailedStateLoad,
            stopAutoUpdateLoop,
            syncNativeBreakStatus,
            ui,
            updateStatus,
            wakeEmulationLoop
        }),
        ...createInputCommands({
            state,
            native,
            ensureRomLoaded,
            resumeInput: () => runCommand("resume", {}),
            renderHotkey,
            saveKeymap,
            setKey,
            setTouchState,
            toButtonList,
            waitChecked,
            waitForInputWindow,
            inputTaskManager,
            getInputParentSignal
        }),
        ...createDisassemblyCommands({
            bytesFromFlexibleParams,
            ensureRomLoaded,
            ensureWasmReady,
            formatDisassemblyText,
            getPc,
            getRegisters,
            instructionWidthForMode,
            modeNumber,
            native,
            opcodeWordsFromInput,
            parseAddress,
            parseNumber,
            shouldIncludeDisassemblyBytes,
            u16FromBytes,
            u32FromBytes,
            ui
        }),
        ...createUtilityCommands({
            ensureWasmReady,
            native,
            splitBinaryBits
        }),
        ...createMemoryCommands({
            applyFreezes,
            bigEndianValue,
            bytesFromFlexibleParams,
            ensureRomLoaded,
            hex,
            log,
            matchSearchCondition,
            memorySearchRangeKey,
            memorySearchRanges,
            native,
            openPicker,
            parseAddress,
            parseNumber,
            readFileFromInput,
            readSized,
            renderFreezes,
            renderMemoryDump,
            state,
            swap16,
            swap32,
            ui
        }),
        ...createDebuggerControlCommands({
            breakpointOwners,
            copyText,
            ensureReady,
            ensureRomLoaded,
            getPc,
            hex,
            instructionWidthForMode,
            native,
            parseAddress,
            publicCallStackData,
            publicOtherCoroutines,
            readCallStackData,
            renderBreakpoints,
            renderCallStack,
            resume: (params) => commands.resume(params),
            runDebuggerInstruction,
            runTraceStepper,
            runUntilNextBranchOrReturn,
            runUntilTrueNextBranch,
            state,
            status: (params) => commands.status(params),
            ui,
            updateStatus
        }),
        ...createScriptCommands({
            state,
            ui,
            startPersistentScript,
            stopPersistentScript,
            scriptSummary,
            listPScriptMcps,
            callPScriptMcp,
            renderScriptConsole,
            runSandboxBoundarySelfTest,
            runIsolatedScript,
            runCommand
        }),
        ...createFeatureCommands({ native, ui, uiInteractionLock }),
    };
    
    Object.assign(commands, {
        reg: commands.memoryGetRegister,
        regw: commands.memorySetRegister,
        read8: commands.memoryReadByte,
        read16: commands.memoryReadWord,
        read32: commands.memoryReadDword,
        write8: commands.memoryWriteByte,
        write16: commands.memoryWriteWord,
        write32: commands.memoryWriteDword
    });
    return commands;
}
