export function createAppState() {
    return {
        module: null,
        moduleInitPromise: null,
        scriptLoadPromise: null,
        nativeInitState: "uninitialized",
        emulatorBundleLoaded: false,
        emulatorLoadError: null,
        ready: false,
        running: false,
        paused: true,
        render: true,
        audio: false,
        speed: 1,
        scale: 2,
        rotation: 0,
        frame: 0,
        keys: 0,
        touch: { active: false, x: 0, y: 0 },
        selectedCpu: "arm9",
        breakpoints: [],
        breakpointPolicy: "allow",
        nextBreakpointId: 1,
        freezes: [],
        recentFiles: [],
        previousRegisters: null,
        lastBreakKey: "",
        breakLabel: "",
        keymap: { KeyX: "A", KeyZ: "B", KeyA: "X", KeyS: "Y", KeyQ: "L", KeyW: "R", Enter: "Start", ShiftRight: "Select", ArrowUp: "Up", ArrowDown: "Down", ArrowLeft: "Left", ArrowRight: "Right" },
        buttons: { A: 0, B: 1, Select: 2, Start: 3, Right: 4, Left: 5, Up: 6, Down: 7, R: 8, L: 9, X: 10, Y: 11 },
        fns: {},
        audioContext: null,
        audioNextTime: 0,
        imageData: null,
        loadingFile: false,
        fileTransactionActive: false,
        fileTransactionBoundaryActive: false,
        fileTransactionOwner: null,
        fileTransactionReason: "",
        fileTransactionSerial: 0,
        lastTick: performance.now(),
        lastSaveFlush: 0,
        saveFlushBlockedUntil: 0,
        romSize: 0,
        romName: "",
        romBytes: null,
        pendingRomCandidate: null,
        frameBudget: 0,
        effectiveFps: 0,
        fpsSampleTime: performance.now(),
        fpsSampleFrame: 0,
        search: { snapshot: null, ranges: null, addresses: null, candidateSetComplete: true, address: 0, length: 0, size: 1, rangeKey: "" },
        highlightedDisasmAddress: null,
        highlightedCallstackAddress: null,
        highlightedCallstackCpsr: null,
        selectedCallstackLaneId: null,
        knownSlots: ["dq9-debug"],
        screenshotCooldownUntil: 0,
        followPc: true,
        autoUpdate: { enabled: false, hz: 1, timer: 0 },
        breakRefreshPending: false,
        breakRefreshTimer: 0,
        breakRefreshKey: "",
        scripts: new Map(),
        nextScriptId: 1,
        nextScriptTriggerId: 1,
        activeScriptId: null,
        scriptTriggers: [],
        pendingScriptEvents: new Map(),
        nextScriptEventId: 1,
        nextScriptCallbackToken: 1,
        lastScriptError: null,
        explicitPauseSerial: 0,
        scriptStartGeneration: 0,
        analysisBaselines: new Map(),
        romGeneration: 0,
        nativeBreakSerial: 0,
        currentBreakIdentity: null,
        breakpointsInSync: true,
        nativeFault: false,
        activeOperation: null,
        operationSerial: 0,
        breakSerial: 0,
        completedFrameSerial: 0,
        screenValid: false,
        framesSinceStateLoad: 0,
        stateLoadSerial: 0,
        traceEnabled: true,
        traceStateSynchronized: true
    };
}
