export const UI_STRINGS = [
['接続済み','Connected'],['上画面','Top screen'],['下画面','Bottom screen'],['横幅を変更','Resize width'],['実行を停止し、このエミュレーターを破棄','Stop and destroy this instance'],['表示アドレス (hex / PC)','Display address (hex / PC)'],['命令セット','Instruction set'],['自動','Auto'],['表示','Show'],['ここまで','Run here'],['ステート名','State name'],['DST / ML を開く','Open DST / ML'],['保存したステートはありません。','No saved states.'],['1命令進む','Execute one instruction'],['呼び出しを飛び越し、それ以外は1命令進む','Step over calls; otherwise execute one instruction'],['ゲーム画面。方向キー、X=A、Z=B、S=X、A=Y、Q=L、W=R、Enter=START、Shift=SELECT','Game screen. Arrows, X=A, Z=B, S=X, A=Y, Q=L, W=R, Enter=START, Shift=SELECT'],['方向キー / X:A Z:B S:X A:Y Q:L W:R Enter:START Shift:SELECT','Arrows / X:A Z:B S:X A:Y Q:L W:R Enter:START Shift:SELECT'],
['ツール','Tools'],['ツールの順序','Tool order'],['追加するツール','Add tool'],['ツールを追加','Add a tool'],['＋ インスタンス','＋ Instance'],['ROMを開く','Open ROM'],['起動中…','Starting…'],['準備完了','Ready'],['対象','Target'],['ROM読込先','ROM target'],['ROM読込範囲','ROM load scope'],['このインスタンス','This instance'],['全インスタンス','All instances'],['台数','Count'],['一括読込台数','Instance count'],['配置モード','Layout'],['一覧','Grid'],['自由配置','Free layout'],['作業領域','Workspace'],['最小化','Minimize'],['展開','Expand'],['閉じる','Close'],
['エミュレータ','Emulator'],['デバッガ','Debugger'],['メモリ','Memory'],['逆アセンブル','Disassembly'],['レジスタ','Registers'],['ブレークポイント','Breakpoints'],['ローカル通信','Local wireless'],['スクリプト','Script'],['常駐スクリプト','Persistent script'],['入力','Input'],['ステート','State'],['セーブデータ','Save data'],['コールスタック','Call stack'],['DLCファイル','DLC files'],['全体保存 .mel','Workspace .mel'],
['更新','Refresh'],['設定','Set'],['追加','Add'],['削除','Delete'],['消去','Clear'],['実行','Run'],['停止','Pause'],['中断','Suspend'],['再開','Resume'],['リセット','Reset'],['音声 OFF','Audio OFF'],['音声 ON','Audio ON'],['キー入力','Keyboard'],['入力連動なし','No input link'],['入力連動先','Input link'],['ROM未読込','No ROM'],['表示を停止','Freeze display'],['復号・再構成済み','Decoded / reassembled'],['DQ9 WFC 接続','Connect DQ9 WFC'],['ネットワーク切断','Disconnect network'],
['時刻','Time'],['方向','Direction'],['送信元','Source'],['宛先','Destination'],['プロトコル','Protocol'],['長さ','Length'],['内容','Content'],['受信データはまだありません。','No packets yet.'],['ファイルを開く','Open files'],['次回も使用','Use next time'],['インスタンス未作成','Instance not created'],['ファイル名','Filename'],['全体を保存','Save workspace'],['.mel を開く','Open .mel'],['保存中…','Saving…'],['復元中…','Restoring…'],
['読取','Read'],['書込','Write'],['読書込','Read / write'],['未定義命令','Undefined instruction'],['メモリ表示','Memory view'],['アドレス (hex)','Address (hex)'],['アドレス','Address'],['検索','Search'],['検索開始','Search'],['検索を中断','Cancel search'],['読込','Load'],['保存','Save'],['保存先','Destination'],['PCへ','Go to PC'],['PCへ移動','Go to PC'],['1命令','Step into'],['ステップ実行','Step into'],['ステップオーバー','Step over'],['スマートステップ','Smart step'],['実行位置まで','Run to address'],['バイト数','Byte count'],['値 (hex)','Value (hex)'],['長さ (bytes)','Length (bytes)'],
['読込中…','Loading…'],['保存済み','Saved'],['ファイルから読込','Load file'],['ファイルに保存','Export file'],['名前を付けて保存','Save as'],['ブラウザーに保存','Save in browser'],['ブラウザに保存','Save in browser'],['ブラウザーから読込','Load from browser'],['ブラウザから読込','Load from browser'],['スロット','Slot'],['保存名','Save name'],['状態','State'],['名前','Name'],['サイズ','Size'],['フォルダー','Folder'],['ファイル','File'],['選択','Select'],['テキスト','Text'],['バイナリ','Binary'],['テキスト保存','Save text'],['ファイルを追加','Add files'],['フォルダーを追加','Add folder'],['フォルダを追加','Add folder'],['書き出し','Export'],['ダウンロード','Export'],['選択を削除','Delete selected'],['パス','Path'],['上へ','Move up'],['下へ','Move down'],
['記録開始','Record'],['記録停止','Stop recording'],['再生','Play'],['再生停止','Stop playback'],['連続入力','Repeat input'],['回数','Count'],['押下','Press'],['解放','Release'],['開始','Start'],['終了','Stop'],['ソース','Source'],['コード','Code'],['非同期','Async'],['起動','Start'],['再起動','Restart'],['関数','Function'],['呼び出し','Invoke'],['戻り先','Return'],['現在位置','Current PC'],['フレーム','Frame'],['稼働中','Running'],['停止中','Paused'],['BIOSとファームウェア','BIOS and firmware'],['内蔵','Built-in'],['実機','Native'],['読込済み','Loaded']
];
